default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ordering_system_DAS_development

test:
  <<: *default
  database: ordering_system_DAS_test

production:
  <<: *default
  database: ordering_system_DAS_production
  username: ordering_system_DAS
  password: <%= ENV['ORDERING_SYSTEM_DAS_DATABASE_PASSWORD'] %>
