# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d676fa74ad5c517c4e43f009a09b4396eb944faf520e474148da445f69375e00c845d6750fa441d160a510b287fadf743c0d2a2432fa7f2025ef4137854bbdd

test:
  secret_key_base: ca97b898bf00d66945222b21a79a048327505961f007dee1baf16e939062d69229c849dd4e324950166fa139736d70637d97649e17bf3a6fb6d7d9e029bc7db8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
